/* eslint-disable max-len */
import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';

import {
    useAddress,
    useChainId,
    useContract,
    useContractRead,
    useDisconnect,
    useMetamask,
} from '@thirdweb-dev/react';

import Header from '../components/Header';
import Login from '../components/Login';
import Loader from '../components/Loader';

const Home: NextPage = () => {
    const address = useAddress();
    const { contract, isLoading, error } = useContract(
        '0x0D38752bA4EB18CCDac708E3eE10E37132056d05',
    );

    const { data: remainingTickets, isLoading: contractDataLoading } =
        useContractRead(contract, 'RemainingTickets');

    const [quantity, setQuantity] = useState(1);

    if (!address) {
        return <Login />;
    }

    // if (isLoading) {
    //     return <Loader />;
    // }

    return (
        <div className="bg-slate-900 min-h-screen flex flex-col">
            <Head>
                <title>Crypto Lottery</title>
                <meta
                    content="Generated by create next app"
                    name="description"
                />
                <link href="/images/favicon.png" rel="icon" />
            </Head>

            <main>
                <Header />

                {/* The Next Draw Box */}
                <div className="space-y-5 md:space-y-0 m-5 md:flex md:flex-row items-start justify-center md:space-x-5">
                    <div className="stats-container">
                        <h2 className="text-5xl text-white font-semibold text-center">
                            The Next Draw
                        </h2>

                        <div className="flex justify-between p-2 space-x-2">
                            <div className="stats">
                                <h3 className="text-sm">Total Pool</h3>
                                <p className="text-xl">0.1 ETH</p>
                            </div>
                            <div className="stats">
                                <h3 className="text-sm">Tickets Remaining</h3>
                                <p className="text-xl">100</p>
                            </div>
                        </div>

                        {/* Countdown timer */}
                        {/*...*/}
                    </div>

                    <div className="stats-container space-y-2">
                        <div className="stats-container">
                            <div className="flex justify-between items-center text-white pb-2">
                                <h2>Price per ticket</h2>
                                <p>0.01 MATIC</p>
                            </div>

                            <div className="flex text-white items-center space-x-2 bg-slate-900 border-slate-600 border p-4">
                                <p>TICKETS</p>
                                <input
                                    className="flex w-full bg-transparent text-right outline-none"
                                    max={10}
                                    min={1}
                                    onChange={e =>
                                        setQuantity(Number(e.target.value))
                                    }
                                    type="number"
                                    value={quantity}
                                />
                            </div>

                            <div className="space-y-2 mt-5">
                                <div className="flex items-center justify-between text-blue-500 text-sm italic font-extrabold">
                                    <p>Total cost of tickets</p>
                                    <p>0.999</p>
                                </div>
                                <div className="flex items-center justify-between text-blue-500 text-xs italic">
                                    <p>Service fees</p>
                                    <p>0.001 MATIC</p>
                                </div>
                                <div className="flex items-center justify-between text-blue-500 text-xs italic">
                                    <p>+ Network Fees</p>
                                    <p>TBC</p>
                                </div>
                            </div>

                            <button
                                className="mt-5 w-full bg-gradient-to-br 
            from-blue-500 to-slate-800 px-10 py-5 rounded-md
             text-white shadow-xl disabled:from-gray-600 disabled:to-gray-600 disabled:text-gray-100 disabled:cursor-not-allowed"
                            >
                                Buy tickets
                            </button>
                        </div>
                    </div>
                </div>

                {/* The Price per ticket box */}
                <div></div>
            </main>
        </div>
    );
};

export default Home;
